=== anikom15/scanline-classic/tools/presetgen/preset.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Preset",
  "type": "object",
  "properties": {
    "filename": { "type": "string" },
    "type": { "type": "string" },
    "title": { "type": "string" },
    "description": { "type": "string" },
    "pipeline_root": { "type": "string" },
    "pipelines": {
      "type": "array",
      "items": { "type": "string" }
    },
    "parameter_root": { "type": "string" },
    "parameter_sets": {
      "type": "array",
      "items": { "type": "string" }
    },
    "parameter_overrides": {
      "type": "object",
      "additionalProperties": true
    }
  },
  "required": [
    "filename",
    "type",
    "title",
    "description",
    "pipeline_root",
    "pipelines"
  ],
  "additionalProperties": true
}

=== anikom15/scanline-classic/presetdata/input/hdtv/psx-eu.json
{
  "filename" : "psx-eu",
  "type" : "hdtv",
  "title" : "PlayStation RGB shader set (PALplus)",
  "description" : "Simulates PlayStation connected via SCART to a widescreen set.  For 4:3 content or 16:9 with widescreen hack; for native 16:9 (e.g. Wipeout 3), see psx-eu-ws.",
  "pipeline_root" : "../../pipelines",
  "pipelines" : [
    "misc/menu.json",
    "misc/frame-tv625.json",
    "sys/rgb.json",
    "disp/crt-hd.json",
    "misc/post.json"
  ],
  "parameter_root" : "../../params",
  "parameter_sets" : [
    "sys/psx/base.json",
    "sys/psx/pal.json",
    "disp/palplus.json",
    "disp/tv-palplus.json",
    "disp/tvl-800.json"
  ],
  "parameter_overrides" : {
  }
}

=== anikom15/scanline-classic/presetdata/input/professional/n64-gb-rf.json
{
  "filename" : "n64-gb-rf",
  "type" : "professional",
  "title" : "Nintendo 64 RF shader set (PAL-I)",
  "description" : "RF output is available with the appropriate RF modulator.",
  "pipeline_root" : "../../pipelines",
  "pipelines" : [
    "misc/menu-composite.json",
    "misc/frame-tv625.json",
    "sys/component-rf.json",
    "disp/crt.json",
    "misc/post.json"
  ],
  "parameter_root" : "../../params",
  "parameter_sets" : [
    "sys/n64/base.json",
    "sys/n64/pal.json",
    "misc/rf-pali.json",
    "disp/pal.json",
    "disp/trinitron.json",
    "disp/tvl-600.json"
  ],
  "parameter_overrides" : {
  }
}

=== anikom15/scanline-classic/presetdata/input/consumer/3do.json
{
  "filename" : "3do",
  "type" : "consumer",
  "title" : "3DO composite shader set",
  "description" : "Composite output is available on all 3DO models with the included cable.",
  "pipeline_root" : "../../pipelines",
  "pipelines" : [
    "sys/3do-special.json",
    "misc/menu-digital-composite-upsample.json",
    "misc/frame-digital-780.json",
    "sys/digital-composite.json",
    "disp/crt.json",
    "misc/post.json"
  ],
  "parameter_root" : "../../params",
  "parameter_sets" : [
    "sys/3do/base.json",
    "sys/3do/ntsc.json",
    "sys/3do/composite.json",
    "disp/ntscj.json",
    "disp/trinitron.json",
    "disp/consumer-color-ntsc.json",
    "disp/tvl-450.json"
  ],
  "parameter_overrides" : {
  }
}

=== anikom15/scanline-classic/presetdata/input/professional/md-gb-rf.json
{
  "filename" : "md-gb-rf",
  "type" : "professional",
  "title" : "Mega Drive RF shader set (PAL-I)",
  "description" : "United Kingdom and commonwealth countries used PAL-I, which has higher bandwidth than PAL-G.",
  "pipeline_root" : "../../pipelines",
  "pipelines" : [
    "misc/menu-rf-yc.json",
    "misc/frame-tv625.json",
    "sys/yc-rf.json",
    "disp/crt-625.json",
    "misc/post.json"
  ],
  "parameter_root" : "../../params",
  "parameter_sets" : [
    "sys/md/base.json",
    "sys/md/pal.json",
    "misc/rf-pali.json",
    "disp/pal.json",
    "disp/trinitron.json",
    "disp/deflicker.json",
    "disp/tvl-600.json"
  ],
  "parameter_overrides" : {
  }
}

=== anikom15/scanline-classic/presetdata/input/professional/3do-eu-composite.json
{
  "filename" : "3do-eu-composite",
  "type" : "professional",
  "title" : "3DO composite shader set (PAL)",
  "description" : "Composite video output is the standard output on all 3DO models.",
  "pipeline_root" : "../../pipelines",
  "pipelines" : [
    "sys/3do-special.json",
    "misc/menu-composite-direct.json",
    "misc/frame-tv625.json",
    "sys/direct-composite.json",
    "disp/crt.json",
    "misc/post.json"
  ],
  "parameter_root" : "../../params",
  "parameter_sets" : [
    "sys/3do/base.json",
    "sys/3do/pal.json",
    "disp/pal.json",
    "disp/trinitron.json",
    "disp/deflicker.json",
    "disp/tvl-600.json"
  ],
  "parameter_overrides" : {
  }
}

=== anikom15/scanline-classic/presetdata/input/consumer/snes-eu.json
{
  "filename" : "snes-eu",
  "type" : "consumer",
  "title" : "SNES composite shader set (PAL)",
  "description" : "All models included an A/V cable with the console.  French consoles included a composite to RGB converter (despite the console having native RGB output).",
  "pipeline_root" : "../../pipelines",
  "pipelines" : [
    "misc/menu-composite.json",
    "misc/frame-tv625.json",
    "sys/component-composite.json",
    "disp/crt.json",
    "misc/post.json"
  ],
  "parameter_root" : "../../params",
  "parameter_sets" : [
    "sys/sfc/base.json",
    "sys/sfc/pal.json",
    "disp/pal.json",
    "disp/tv.json",
    "disp/consumer-color-pal.json",
    "disp/tvl-450.json"
  ],
  "parameter_overrides" : {
  }
}

=== anikom15/scanline-classic/presetdata/input/hdtv/3do-240p.json
{
  "filename" : "3do-240p",
  "type" : "hdtv",
  "title" : "3DO S-Video shader set (240p, Hi-Vision)",
  "description" : "Simulates a S-Video connection to a Hi-Vision TV.  While the 3DO is 480i only, some users may prefer the scanline clarity from a higher resolution screen.",
  "pipeline_root" : "../../pipelines",
  "pipelines" : [
    "sys/3do-special-240p.json",
    "misc/menu-digital-video-upsample.json",
    "misc/frame-digital-780.json",
    "sys/digital-svideo.json",
    "disp/crt-hd.json",
    "misc/post.json"
  ],
  "parameter_root" : "../../params",
  "parameter_sets" : [
    "sys/3do/base.json",
    "sys/3do/ntsc.json",
    "sys/3do/svideo.json",
    "sys/3do/240p.json",
    "disp/hdtv.json",
    "disp/trinitron-hv.json",
    "disp/tvl-800.json"
  ],
  "parameter_overrides" : {
  }
}

=== anikom15/scanline-classic/presetdata/input/professional/psx-eu-svideo.json
{
  "filename" : "psx-eu-svideo",
  "type" : "professional",
  "title" : "PlayStation S-Video shader set (PAL)",
  "description" : "S-Video was available on all PSX models.",
  "pipeline_root" : "../../pipelines",
  "pipelines" : [
    "misc/menu-svideo.json",
    "misc/frame-tv625.json",
    "sys/svideo.json",
    "disp/crt.json",
    "misc/post.json"
  ],
  "parameter_root" : "../../params",
  "parameter_sets" : [
    "sys/psx/base.json",
    "sys/psx/pal.json",
    "disp/pal.json",
    "disp/trinitron.json",
    "disp/deflicker.json",
    "disp/tvl-600.json"
  ],
  "parameter_overrides" : {
  }
}
