=== anikom15/scanline-classic/tools/presetgen/preset.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Preset",
  "type": "object",
  "properties": {
    "filename": { "type": "string" },
    "type": { "type": "string" },
    "title": { "type": "string" },
    "description": { "type": "string" },
    "pipeline_root": { "type": "string" },
    "pipelines": {
      "type": "array",
      "items": { "type": "string" }
    },
    "parameter_root": { "type": "string" },
    "parameter_sets": {
      "type": "array",
      "items": { "type": "string" }
    },
    "parameter_overrides": {
      "type": "object",
      "additionalProperties": true
    }
  },
  "required": [
    "filename",
    "type",
    "title",
    "description",
    "pipeline_root",
    "pipelines"
  ],
  "additionalProperties": true
}

=== anikom15/scanline-classic/presetdata/input/arcade/nvs.json
{
  "filename" : "nvs",
  "type" : "arcade",
  "title" : "Nintendo Vs. System shader set",
  "description" : "Arcade version of the Famicom/NES",
  "pipeline_root" : "../../pipelines",
  "pipelines" : [
    "sys/famicom-rgb.json",
    "disp/crt.json",
    "misc/post.json"
  ],
  "parameter_root" : "../../params",
  "parameter_sets" : [
    "sys/sfc/base.json",
    "sys/sfc/ntsc.json",
    "disp/ntscj.json",
    "disp/arcade-flat.json",
    "disp/tvl-400.json"
  ],
  "parameter_overrides" : {
  }
}

=== anikom15/scanline-classic/presetdata/input/professional/md-fr-rgb.json
{
  "filename" : "md-fr_md2-eu",
  "type" : "professional",
  "title" : "Mega Drive RGB shader set",
  "description" : "RGB was officially supported in France, however RGB output is available on most Mega Drives.  An official cable was released for all European Mega Drive IIs.",
  "pipeline_root" : "../../pipelines",
  "pipelines" : [
    "misc/menu.json",
    "misc/frame-tv625.json",
    "sys/rgb.json",
    "disp/crt.json",
    "misc/post.json"
  ],
  "parameter_root" : "../../params",
  "parameter_sets" : [
    "sys/md/base.json",
    "sys/md/pal.json",
    "disp/pal.json",
    "disp/trinitron.json",
    "disp/deflicker.json",
    "disp/tvl-600.json"
  ],
  "parameter_overrides" : {
  }
}

=== anikom15/scanline-classic/presetdata/input/consumer/gen.json
{
  "filename" : "gen",
  "type" : "consumer",
  "title" : "Genesis composite shader set",
  "description" : "A/V was included for all NTSC consoles.",
  "pipeline_root" : "../../pipelines",
  "pipelines" : [
    "misc/menu-composite-yc.json",
    "misc/frame-tv525.json",
    "sys/yc-composite.json",
    "disp/crt.json",
    "misc/post.json"
  ],
  "parameter_root" : "../../params",
  "parameter_sets" : [
    "sys/md/base.json",
    "sys/md/ntsc.json",
    "disp/ntsc.json",
    "disp/tv.json",
    "disp/consumer-color-ntsc.json",
    "disp/tvl-450.json"
  ],
  "parameter_overrides" : {
  }
}

=== anikom15/scanline-classic/presetdata/input/professional/3do-us-svideo.json
{
  "filename" : "3do-us",
  "type" : "professional",
  "title" : "3DO S-Video shader set (NTSC-M)",
  "description" : "S-Video output is available on all 3DO models with the appropriate cable.",
  "pipeline_root" : "../../pipelines",
  "pipelines" : [
    "sys/3do-special.json",
    "misc/menu-digital-video-upsample.json",
    "misc/frame-digital-780.json",
    "sys/digital-svideo.json",
    "disp/crt.json",
    "misc/post.json"
  ],
  "parameter_root" : "../../params",
  "parameter_sets" : [
    "sys/3do/base.json",
    "sys/3do/ntsc.json",
    "sys/3do/svideo.json",
    "disp/ntsc.json",
    "disp/trinitron.json",
    "disp/tvl-600.json"
  ],
  "parameter_overrides" : {
  }
}

=== anikom15/scanline-classic/presetdata/input/professional/sfc-composite.json
{
  "filename" : "sfc-composite_sfcjr",
  "type" : "professional",
  "title" : "Super Famicom composite shader set",
  "description" : "All models included an A/V cable with the console.",
  "pipeline_root" : "../../pipelines",
  "pipelines" : [
    "misc/menu-composite.json",
    "misc/frame-1716x526.json",
    "sys/component-composite.json",
    "disp/crt.json",
    "misc/post.json"
  ],
  "parameter_root" : "../../params",
  "parameter_sets" : [
    "sys/sfc/base.json",
    "disp/ntscj.json",
    "disp/trinitron.json",
    "disp/tvl-600.json"
  ],
  "parameter_overrides" : {
  }
}

=== anikom15/scanline-classic/presetdata/input/consumer/snes.json
{
  "filename" : "snes_snesmini",
  "type" : "consumer",
  "title" : "SNES composite shader set",
  "description" : "All models included an A/V cable with the console.",
  "pipeline_root" : "../../pipelines",
  "pipelines" : [
    "misc/menu-composite.json",
    "misc/frame-tv525.json",
    "sys/component-composite.json",
    "disp/crt.json",
    "misc/post.json"
  ],
  "parameter_root" : "../../params",
  "parameter_sets" : [
    "sys/sfc/base.json",
    "sys/sfc/ntsc.json",
    "disp/ntsc.json",
    "disp/tv.json",
    "disp/consumer-color-ntsc.json",
    "disp/tvl-450.json"
  ],
  "parameter_overrides" : {
  }
}

=== anikom15/scanline-classic/presetdata/input/consumer/n64.json
{
  "filename" : "n64",
  "type" : "consumer",
  "title" : "Nintendo 64 composite shader set",
  "description" : "All models have composite video as standard.",
  "pipeline_root" : "../../pipelines",
  "pipelines" : [
    "misc/menu-composite.json",
    "misc/frame-tv525.json",
    "sys/component-composite.json",
    "disp/crt.json",
    "misc/post.json"
  ],
  "parameter_root" : "../../params",
  "parameter_sets" : [
    "sys/n64/base.json",
    "sys/n64/ntsc.json",
    "disp/ntscj.json",
    "disp/trinitron.json",
    "disp/consumer-color-ntsc.json",
    "disp/tvl-450.json"
  ],
  "parameter_overrides" : {
  }
}

=== anikom15/scanline-classic/presetdata/sfc-pro.json
{
  "filename" : "sfc",
  "type" : "professional",
  "title" : "Super Famicom RGB shader set",
  "description" : "All standard models, but not the Jr. and Mini models, have an RGB output available without modification. However, its use was only officially supported in Japan with the OEM JP-21 connector.",
  "pipeline_root" : "pipelines",
  "pipelines" : [
    "misc/pre.json",
    "sys/rgb.json",
    "disp/crt.json",
    "misc/post.json"
  ],
  "parameter_root" : "params",
  "parameter_sets" : [
    "sys/sfc/base.json",
    "disp/ntscj.json",
    "disp/trinitron-600.json"
  ],
  "parameter_overrides" : {
  }
}
