=== anikom15/scanline-classic/tools/presetgen/preset.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Preset",
  "type": "object",
  "properties": {
    "filename": { "type": "string" },
    "type": { "type": "string" },
    "title": { "type": "string" },
    "description": { "type": "string" },
    "pipeline_root": { "type": "string" },
    "pipelines": {
      "type": "array",
      "items": { "type": "string" }
    },
    "parameter_root": { "type": "string" },
    "parameter_sets": {
      "type": "array",
      "items": { "type": "string" }
    },
    "parameter_overrides": {
      "type": "object",
      "additionalProperties": true
    }
  },
  "required": [
    "filename",
    "type",
    "title",
    "description",
    "pipeline_root",
    "pipelines"
  ],
  "additionalProperties": true
}

=== anikom15/scanline-classic/presetdata/input/professional/md-br-rf.json
{
  "filename" : "md-br-rf",
  "type" : "professional",
  "title" : "Mega Drive RF shader set (Brazil variant)",
  "description" : "Most TVs in Brazil were RF only, however A/V output was also available",
  "pipeline_root" : "../../pipelines",
  "pipelines" : [
    "misc/menu-rf-yc.json",
    "misc/frame-tv525.json",
    "sys/yc-rf.json",
    "disp/crt.json",
    "misc/post.json"
  ],
  "parameter_root" : "../../params",
  "parameter_sets" : [
    "sys/md/base.json",
    "sys/md/palm.json",
    "disp/palm.json",
    "disp/trinitron.json",
    "disp/tvl-600.json"
  ],
  "parameter_overrides" : {
  }
}

=== anikom15/scanline-classic/presetdata/input/professional/md-fr.json
{
  "filename" : "md-fr",
  "type" : "professional",
  "title" : "Mega Drive RGB shader set",
  "description" : "RGB was officially supported in France, however RGB output is available on most Mega Drives.",
  "pipeline_root" : "../../pipelines",
  "pipelines" : [
    "misc/menu.json",
    "misc/frame-tv625.json",
    "sys/rgb.json",
    "disp/crt.json",
    "misc/post.json"
  ],
  "parameter_root" : "../../params",
  "parameter_sets" : [
    "sys/md/base.json",
    "sys/md/pal.json",
    "disp/pal.json",
    "disp/trinitron.json",
    "disp/deflicker.json",
    "disp/tvl-600.json"
  ],
  "parameter_overrides" : {
  }
}

=== anikom15/scanline-classic/presetdata/input/arcade/nss.json
{
  "filename" : "nss",
  "type" : "arcade",
  "title" : "Nintendo Super System shader set",
  "description" : "Arcade variant of the SNES",
  "pipeline_root" : "../../pipelines",
  "pipelines" : [
    "misc/menu.json",
    "misc/frame-tv525.json",
    "sys/rgb.json",
    "disp/crt.json",
    "misc/post.json"
  ],
  "parameter_root" : "../../params",
  "parameter_sets" : [
    "sys/sfc/base.json",
    "sys/sfc/ntsc.json",
    "disp/ntscj.json",
    "disp/arcade-tvstyle.json",
    "disp/tvl-400.json"
  ],
  "parameter_overrides" : {
  }
}

=== anikom15/scanline-classic/presetdata/input/hdtv/3do.json
{
  "filename" : "3do",
  "type" : "hdtv",
  "title" : "3DO S-Video shader set (Hi-Vision)",
  "description" : "Simulates a S-Video connection to a Hi-Vision TV.  While the 3DO is 480i only, some users may prefer the scanline clarity from a higher resolution screen.",
  "pipeline_root" : "../../pipelines",
  "pipelines" : [
    "sys/3do-special.json",
    "misc/menu-digital-video-upsample.json",
    "misc/frame-digital-780x1125.json",
    "sys/digital-svideo.json",
    "disp/crt.json",
    "misc/post.json"
  ],
  "parameter_root" : "../../params",
  "parameter_sets" : [
    "sys/3do/base.json",
    "sys/3do/ntsc.json",
    "sys/3do/svideo.json",
    "disp/hdtv.json",
    "disp/trinitron-hv.json",
    "disp/tvl-800.json"
  ],
  "parameter_overrides" : {
  }
}

=== anikom15/scanline-classic/presetdata/input/professional/md-rf.json
{
  "filename" : "md-rf",
  "type" : "professional",
  "title" : "Mega Drive RF shader set (NTSC-J)",
  "description" : "",
  "pipeline_root" : "../../pipelines",
  "pipelines" : [
    "misc/menu-rf-yc.json",
    "misc/frame-tv525.json",
    "sys/yc-rf.json",
    "disp/crt.json",
    "misc/post.json"
  ],
  "parameter_root" : "../../params",
  "parameter_sets" : [
    "sys/md/base.json",
    "sys/md/ntsc.json",
    "misc/rf-ntsc.json",
    "disp/ntscj.json",
    "disp/rf-ntsc.json",
    "disp/trinitron.json",
    "disp/tvl-600.json"
  ],
  "parameter_overrides" : {
  }
}

=== anikom15/scanline-classic/presetdata/input/professional/gen-composite.json
{
  "filename" : "gen",
  "type" : "professional",
  "title" : "Genesis composite shader set",
  "description" : "A/V was included for all NTSC consoles.",
  "pipeline_root" : "../../pipelines",
  "pipelines" : [
    "misc/menu-composite-yc.json",
    "misc/frame-tv525.json",
    "sys/yc-composite.json",
    "disp/crt.json",
    "misc/post.json"
  ],
  "parameter_root" : "../../params",
  "parameter_sets" : [
    "sys/md/base.json",
    "sys/md/ntsc.json",
    "disp/ntsc.json",
    "disp/trinitron.json",
    "disp/tvl-600.json"
  ],
  "parameter_overrides" : {
  }
}

=== anikom15/scanline-classic/presetdata/input/consumer/pceav.json
{
  "filename" : "pceav",
  "type" : "consumer",
  "title" : "PC Engine composite shader set",
  "description" : "The stock PC Engine is RF only, but later peripherals support composite output.  The shader is setup similarly to the SFC, however in reality there is a distinct difference: the SNES generates RGB first and uses a conventional RGB to YPbPr to composite chip.  The PC Engine uses a proprietary chip that outputs RGB and Y/C directly (Pb and Pr are already modulated).  The composite signal is obtained with a discrete analog combiner. Therefore we have appropriated the sys-component shader to represent the Y/C DAC and bypass sys-rgb entirely.  The PC Engine RGB to YPbPr LUT is not applied here.  Use an emulator that outputs the correct colors for composite video.",
  "pipeline_root" : "../../pipelines",
  "pipelines" : [
    "misc/menu-digital-composite.json",
    "misc/frame-digital-1365.json",
    "sys/digital-direct-composite.json",
    "disp/crt.json",
    "misc/post.json"
  ],
  "parameter_root" : "../../params",
  "parameter_sets" : [
    "sys/pce/base.json",
    "disp/ntscj.json",
    "disp/trinitron.json",
    "disp/consumer-color-ntsc.json",
    "disp/tvl-450.json"
  ],
  "parameter_overrides" : {
  }
}

=== anikom15/scanline-classic/presetdata/input/consumer/famicom.json
{
  "filename" : "famicom",
  "type" : "consumer",
  "title" : "Famicom RF shader set",
  "description" : "The original Famicom was RF only",
  "pipeline_root" : "../../pipelines",
  "pipelines" : [
    "sys/famicom-rf.json",
    "disp/crt.json",
    "misc/post.json"
  ],
  "parameter_root" : "../../params",
  "parameter_sets" : [
    "sys/sfc/base.json",
    "sys/sfc/ntsc.json",
    "misc/rf-ntsc.json",
    "disp/ntscj.json",
    "disp/trinitron.json",
    "disp/consumer-color-ntsc.json",
    "disp/tvl-300.json"
  ],
  "parameter_overrides" : {
  }
}
